# Generated by Django 5.0.6 on 2024-05-28 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentsSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('slot_9AM_to_10AM', models.CharField(choices=[('available', 'available'), ('not_available', 'not_available')], db_column='slot_1', default='available', max_length=20)),
                ('slot_10AM_to_11AM', models.CharField(choices=[('available', 'available'), ('not_available', 'not_available')], db_column='slot_2', default='available', max_length=20)),
                ('slot_11AM_to_12PM', models.CharField(choices=[('available', 'available'), ('not_available', 'not_available')], db_column='slot_3', default='available', max_length=20)),
                ('slot_1PM_to_2PM', models.CharField(choices=[('available', 'available'), ('not_available', 'not_available')], db_column='slot_4', default='available', max_length=20)),
                ('slot_2PM_to_3PM', models.CharField(choices=[('available', 'available'), ('not_available', 'not_available')], db_column='slot_5', default='available', max_length=20)),
                ('slot_4PM_to_5PM', models.CharField(choices=[('available', 'available'), ('not_available', 'not_available')], db_column='slot_6', default='available', max_length=20)),
                ('slot_5PM_to_6Pm', models.CharField(choices=[('available', 'available'), ('not_available', 'not_available')], db_column='slot_7', default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booked_date', models.DateField()),
                ('Slot_time', models.CharField(choices=[('slot_9AM_to_10AM', 'slot_9AM_to_10AM'), ('slot_10AM_to_11AM', 'slot_10AM_to_11AM'), ('slot_11AM_to_12PM', 'slot_11AM_to_12PM'), ('slot_1PM_to_2PM', 'slot_1PM_to_2PM'), ('slot_2PM_to_3PM', 'slot_2PM_to_3PM'), ('slot_4PM_to_5PM', 'slot_4PM_to_5PM'), ('slot_5PM_to_6Pm', 'slot_5PM_to_6Pm')], db_column='slot_time', max_length=20)),
                ('add_info', models.CharField(max_length=50)),
                ('service', models.CharField(choices=[('grooming', 'Grooming'), ('hair_cut', 'hair_cut'), ('nail_cutting', 'nail_cutting')], default='grooming', max_length=15)),
                ('pet_id', models.ForeignKey(db_column='pet_id', on_delete=django.db.models.deletion.CASCADE, to='user.pets')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
