# Generated by Django 3.1 on 2024-05-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsschedule',
            name='slot_10AM_to_11AM',
            field=models.BooleanField(db_column='slot_2', default=True),
        ),
        migrations.AlterField(
            model_name='appointmentsschedule',
            name='slot_11AM_to_12PM',
            field=models.BooleanField(db_column='slot_3', default=True),
        ),
        migrations.AlterField(
            model_name='appointmentsschedule',
            name='slot_1PM_to_2PM',
            field=models.BooleanField(db_column='slot_4', default=True),
        ),
        migrations.AlterField(
            model_name='appointmentsschedule',
            name='slot_2PM_to_3PM',
            field=models.BooleanField(db_column='slot_5', default=True),
        ),
        migrations.AlterField(
            model_name='appointmentsschedule',
            name='slot_4PM_to_5PM',
            field=models.BooleanField(db_column='slot_6', default=True),
        ),
        migrations.AlterField(
            model_name='appointmentsschedule',
            name='slot_5PM_to_6Pm',
            field=models.BooleanField(db_column='slot_7', default=True),
        ),
        migrations.AlterField(
            model_name='appointmentsschedule',
            name='slot_9AM_to_10AM',
            field=models.BooleanField(db_column='slot_1', default=True),
        ),
    ]
