# Generated by Django 3.1 on 2024-05-10 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0007_auto_20240509_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booked_date', models.DateField()),
                ('Slot_time', models.CharField(choices=[('slot_9AM_to_10AM', 'slot_9AM_to_10AM'), ('slot_10AM_to_11AM', 'slot_10AM_to_11AM'), ('slot_11AM_to_12PM', 'slot_11AM_to_12PM'), ('slot_1PM_to_2PM', 'slot_1PM_to_2PM'), ('slot_2PM_to_3PM', 'slot_2PM_to_3PM'), ('slot_4PM_to_5PM', 'slot_4PM_to_5PM'), ('slot_5PM_to_6Pm', 'slot_5PM_to_6Pm')], db_column='slot_time', max_length=20)),
                ('pet_type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Hamster', 'Hamster')], db_column='pet_type', max_length=20)),
                ('add_info', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
