# Generated by Django 3.1 on 2024-05-10 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('appointments', '0008_userapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='pet_type',
            field=models.ForeignKey(db_column='pet_id', on_delete=django.db.models.deletion.CASCADE, to='user.pets'),
        ),
    ]
