# Generated by Django 3.1 on 2024-05-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_auto_20240510_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapp',
            old_name='pet_type',
            new_name='pet_id',
        ),
    ]
