# Generated by Django 3.1 on 2024-05-10 10:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('appointments', '0010_auto_20240510_1540'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserApp',
            new_name='User_App',
        ),
    ]
