# Generated by Django 5.0.6 on 2024-05-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_cart_table_order_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
