# Generated by Django 5.0.6 on 2024-05-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_info_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
