# Generated by Django 5.0.6 on 2024-05-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_info_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='image',
            field=models.FileField(default='images/default.png', upload_to='images'),
        ),
    ]
