# Generated by Django 5.0.6 on 2024-05-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_info_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_history',
        ),
    ]
