# Generated by Django 3.1 on 2024-05-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='images')),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
