# Generated by Django 5.0.6 on 2024-05-28 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=200)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('image', models.ImageField(upload_to='images')),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.CharField(default='mobile', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_history',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('date', models.DateField(auto_now=True)),
                ('address', models.TextField(max_length=100, null=True)),
                ('uid', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_id', models.ForeignKey(db_column='payment_id', on_delete=django.db.models.deletion.CASCADE, to='products.payment_history')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.producttable')),
            ],
        ),
    ]
