# Generated by Django 3.1 on 2024-05-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttable',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
