# Generated by Django 5.0.6 on 2024-05-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_producttable_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttable',
            name='category',
            field=models.CharField(default='mobile', max_length=100),
        ),
    ]
