# Generated by Django 5.0.6 on 2024-05-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_payment_history_order_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_history',
            name='address',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment_history',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
