# Generated by Django 5.0.6 on 2024-05-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order_history_address_payment_history_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_history',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
