# Generated by Django 5.0.6 on 2024-05-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_order_history_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_history',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
